### PR TITLE
Feature update project

### LINKED ISSUE #89: Remove .idea folder from project
Currently the .idea folder, which is usually always excluded from repos, is currently checked in into the repository. It should be deleted and put into the .gitignore.

### LINKED ISSUE #90: Upgrade Gradle to version 7
The project setup didn't work on my machine, so we changed a few things, including upgrading Gradle.

### LINKED ISSUE #91: Set languageLevel to 1.8
The project setup didn't work on my machine, so I changed a few things, including setting the language level in the build.gradle.

### PR DESCRIPTION
**Pull request by masterhanddev**
This PR

* closes #89 
* closes #90 
* closes #91

### CODE REVIEW

**Comment by Jeeppler** [comment]
@masterhanddev is this ready for review? In my opinion @de-jcup is the best reviewer for this pull request.

**Comment by masterhanddev** [comment]
@Jeeppler Yes, it is already ready for review. I also discussed the changes with @de-jcup beforehand, but unfortunately I couldn't assign him as a reviewer.

**Comment by Jeeppler** [comment]
@masterhanddev thanks. I added him as a reviewer.

**Review by de-jcup — APPROVED** [review]
LGTM - looks good to me. Thanx a lot.

**Pull request merged**
